apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cicd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-cicd-demo
  template:
    metadata:
      labels:
        app: flask-cicd-demo
    spec:
      containers:
      - name: app
        image: ghcr.io/gaidaahmed/flask-cicd-demo:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet: { path: "/", port: 5000 }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: "/", port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 10
