name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -q

  docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Define image name
        id: vars
        run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/flask-cicd-demo" >> $GITHUB_OUTPUT
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -t ${{ steps.vars.outputs.IMAGE }}:latest \
                        -t ${{ steps.vars.outputs.IMAGE }}:${{ github.sha }} .
      - name: Push image
        run: |
          docker push ${{ steps.vars.outputs.IMAGE }}:latest
          docker push ${{ steps.vars.outputs.IMAGE }}:${{ github.sha }}
