name: Release Image

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Define image and tag
        id: vars
        run: |
          echo "IMAGE=ghcr.io/${{ github.repository_owner }}/flask-cicd-demo" >> $GITHUB_OUTPUT
          echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker build -t ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }} \
                       -t ${{ steps.vars.outputs.IMAGE }}:latest .

      - name: Push
        run: |
          docker push ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }}
          docker push ${{ steps.vars.outputs.IMAGE }}:latest
